# Generated by Django 4.0.5 on 2022-06-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='prof_id',
            field=models.SlugField(default='NULL', max_length=200, verbose_name='آیدی'),
        ),
    ]
