# Generated by Django 4.0.5 on 2022-06-30 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_prof_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='prof_id',
        ),
    ]
