# Generated by Django 4.0.5 on 2022-06-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_user_prof_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(default='', max_length=250, verbose_name='شغل / حرفه'),
        ),
    ]
