# Generated by Django 4.0.5 on 2022-07-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet',
            field=models.IntegerField(default=0, verbose_name='کیف پول'),
        ),
    ]
