# Generated by Django 4.0.5 on 2022-07-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar.png', upload_to='avatars', verbose_name='آواتار'),
        ),
    ]
