# Generated by Django 4.0.5 on 2022-07-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_user_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet',
            field=models.IntegerField(default=0, verbose_name='کیف پول'),
        ),
        migrations.DeleteModel(
            name='balance',
        ),
    ]
