# Generated by Django 4.0.5 on 2022-07-02 11:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donate',
            fields=[
                ('donate_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0, verbose_name='مبلغ')),
                ('name', models.CharField(default='ناشناس', max_length=250, verbose_name='نام')),
                ('description', models.TextField(default='', max_length=2500, verbose_name='متن')),
                ('donate_to', models.CharField(max_length=250, verbose_name='پرداخت به')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ و زمان')),
                ('payment_status', models.BooleanField(default=False, verbose_name='وضعیت پرداخت')),
            ],
        ),
    ]
