# Generated by Django 4.0.5 on 2022-07-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='tracking_code',
            field=models.IntegerField(default=0, verbose_name='کد پیگیری'),
        ),
    ]
