# Generated by Django 4.0.5 on 2022-07-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_donate_tracking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='tracking_code',
            field=models.IntegerField(unique=True, verbose_name='کد پیگیری'),
        ),
    ]
